#!/usr/bin/env bash
# freeze-case.sh — copy one audit of a real run into a qualification case.
#
# A case is what judge.sh reads for one target, frozen, plus the bean as it was
# when the run happened and the commit the audit ran against. Frozen because the
# run directories live in another repository and the bean files there are
# amended: bean-004 gained ac5 after the run that is its best case, and a case
# that read today's bean would be judging the run against a criterion it never
# had.
#
# usage: freeze-case.sh <run-dir> --repo <git-dir> --target spec|impl|doc|package
#                       --id <case-id> --expect reject|accept
#                       (--pr <n> | --candidate <sha>) [--bean-at <sha>]
#
#   --candidate  the commit the audit's repository search should see. For impl,
#                doc and package that is the built branch; for spec, the base.
#   --pr         take the candidate from the pull request's head (impl/doc/package)
#   --bean-at    the commit to read the bean from (default: the run's gate.json
#                base, which is the main the bean branch was cut from)
#
# It writes inputs/ and a case.json whose answer key is EMPTY. The key is a
# person's (or Claude's) reading of the artifacts and is filled in by hand; a
# case whose key was generated by the thing it measures would measure nothing.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUN=""; REPO=""; TARGET=""; ID=""; EXPECT=""; PR=""; CAND=""; BEAN_AT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="${2:?}"; shift 2 ;;
    --target) TARGET="${2:?}"; shift 2 ;;
    --id) ID="${2:?}"; shift 2 ;;
    --expect) EXPECT="${2:?}"; shift 2 ;;
    --pr) PR="${2:?}"; shift 2 ;;
    --candidate) CAND="${2:?}"; shift 2 ;;
    --bean-at) BEAN_AT="${2:?}"; shift 2 ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    -*) echo "unknown flag: $1" >&2; exit 2 ;;
    *) RUN="$1"; shift ;;
  esac
done
[ -d "$RUN" ] && [ -d "$REPO/.git" ] || { echo "need a run directory and --repo <git dir>" >&2; exit 2; }
case "$TARGET" in spec|impl|doc|package) ;; *) echo "--target spec|impl|doc|package" >&2; exit 2 ;; esac
case "$EXPECT" in reject|accept) ;; *) echo "--expect reject|accept" >&2; exit 2 ;; esac
[[ "$ID" =~ ^[a-z0-9][a-z0-9-]+$ ]] || { echo "--id must be kebab-case" >&2; exit 2; }

if [ -z "$CAND" ] && [ -n "$PR" ]; then
  slug="$(git -C "$REPO" remote get-url origin | sed -E 's#.*github.com[:/]##; s#\.git$##')"
  CAND="$(gh pr view "$PR" --repo "$slug" --json headRefOid --jq .headRefOid)"
fi
[ -n "$CAND" ] || { echo "need --pr or --candidate" >&2; exit 2; }
git -C "$REPO" cat-file -e "$CAND^{commit}" 2>/dev/null \
  || git -C "$REPO" fetch -q origin "$CAND" 2>/dev/null \
  || { [ -n "$PR" ] && git -C "$REPO" fetch -q origin "pull/$PR/head"; } \
  || { echo "candidate $CAND is not in $REPO and could not be fetched" >&2; exit 2; }
CAND="$(git -C "$REPO" rev-parse "$CAND")"

[ -n "$BEAN_AT" ] || BEAN_AT="$(jq -r '.base // empty' "$RUN/gate.json" 2>/dev/null || true)"
[ -n "$BEAN_AT" ] || { echo "no gate.json base in the run; pass --bean-at" >&2; exit 2; }
BEAN_ID="$(jq -r '.bean_id // .bean' "$RUN/run.json")"
BEAN_PATH="$(git -C "$REPO" ls-tree -r --name-only "$BEAN_AT" -- factory/beans | grep -E "/${BEAN_ID}-[^/]*/bean\.yaml$" | head -1)"
[ -n "$BEAN_PATH" ] || { echo "no bean.yaml for $BEAN_ID at $BEAN_AT" >&2; exit 2; }

case "$TARGET" in
  spec)    FILES="spec.md tasks.yaml verify-precheck.json claims-check.json" ;;
  impl)    FILES="spec.md tasks.yaml diff.txt gate.json test-integrity.json" ;;
  doc)     FILES="impl-detail.md spec.md diff.txt" ;;
  package) FILES="run.json steps.jsonl tasks.jsonl gate.json package-check.json" ;;
esac

OUT="$HERE/cases/$ID"
[ ! -e "$OUT" ] || { echo "case $ID already exists; refusing to overwrite a key" >&2; exit 2; }
mkdir -p "$OUT/inputs"
for f in $FILES; do
  [ -f "$RUN/$f" ] && cp "$RUN/$f" "$OUT/inputs/$f"
done
# judge.sh and audit-check read the bean from --bean; a directory named for the
# bean keeps run.json's basename(dirname) lookups honest.
mkdir -p "$OUT/inputs/bean"
git -C "$REPO" show "$BEAN_AT:$BEAN_PATH" > "$OUT/inputs/bean/bean.yaml"
jq -n --arg b "$BEAN_ID" --arg r "$(basename "$RUN")" '{run_id:("qualify-"+$r), bean:$b}' > "$OUT/inputs/run.json.stub"
[ "$TARGET" = package ] || mv "$OUT/inputs/run.json.stub" "$OUT/inputs/run.json"
rm -f "$OUT/inputs/run.json.stub"

jq -n --arg id "$ID" --arg t "$TARGET" --arg e "$EXPECT" --arg run "$(basename "$RUN")" \
  --arg repo "$(git -C "$REPO" remote get-url origin | sed -E 's#.*github.com[:/]##; s#\.git$##')" \
  --arg cand "$CAND" --arg beanat "$(git -C "$REPO" rev-parse "$BEAN_AT")" --arg bp "$BEAN_PATH" \
  --arg pr "$PR" --arg files "$(cd "$OUT/inputs" && ls | paste -sd' ')" '
  {schema:"qualify-case/1.0.0", id:$id, target:$t, expect:$e,
   source:{repo:$repo, run_id:$run, pr:(if $pr=="" then null else ($pr|tonumber) end),
           candidate_sha:$cand, bean_at:$beanat, bean_path:$bp},
   inputs:($files|split(" ")),
   defect:"", answer_key:{why:"", evidence:[]}, anchors:[],
   key_by:"", key_checked_at:""}' > "$OUT/case.json"
printf 'froze %s: %s (%s), candidate %s, bean from %s\n  now write the answer key in %s\n' \
  "$ID" "$TARGET" "$EXPECT" "${CAND:0:12}" "${BEAN_AT:0:12}" "$OUT/case.json"
